googlekeep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("notes.urls")),
]

notes/urls.py
from django.urls import path
from . import views


app_name = "notes"

urlpatterns = [
    path("", view=views.DashboardTemplateView.as_view(), name="dashboard"),
    path("notes/", view=views.NoteListView.as_view(), name="notes_list"),
    path("add/", view=views.CreateNoteView.as_view(), name="create_note"),
    path("note-detail/<int:pk>", view=views.NoteDetailView.as_view(), name="notes-detail"),
    path("done-notes/", view=views.DoneNoteView.as_view(), name="done_notes"),
    path("pending-note/", view=views.PendingNoteView.as_view(), name="pending_notes"),
    path("move-note-trash/<int:pk>", view=views.MoveNoteToTrashView.as_view(), name="move-note-trash"),
    path("trash-note-view/", view=views.TrashNoteView.as_view(), name="trash-note-view"),
    path("restore-note/<int:pk>", view=views.RestoreTrashNote.as_view(), name="restore-note"),
    path("delete-note/<int:pk>", view=views.NoteDeleteView.as_view(), name="delete-note"),
    path("update-note/<int:pk>", view=views.NoteUpdateView.as_view(), name="update-note"),
]

notes/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Note(models.Model):
    title = models.CharField(max_length=200)
    note = models.TextField()
    created_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    deadline = models.DateTimeField(blank=True, null=True)
    trash = models.BooleanField(default=False)
    done = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    CAT_LIST = [
        ('Grocery','Grocery'),
        ('Travel','Travel'),
        ('Sports','Sports'),
        ('Office','Office'),
        ('Food','Food'),
        ('Weekend Plan', 'Weekend Plan'),
        ('Other','Other'),
    ]
    category = models.CharField(max_length=100, choices=CAT_LIST, default="Grocery")

    def __str__(self):
        return f"{self.title} - {self.category}"

    def get_absolute_url(self):
        return reverse('notes:notes-detail', kwargs={'pk' : self.pk})

notes/forms.py
from django import forms
from django.forms import ModelForm, widgets
from notes.models import Note


class NoteForm(ModelForm):
    class Meta:
        model = Note
        # fields = "__all__"
        fields = ["title","note","category"]
        widgets = {
            "title": forms.TextInput(attrs={'class':'form-control'}),
            "note": forms.Textarea(attrs={'class':'form-control'}),
            "category": forms.Select(attrs={'class':'form-control'}),
        }


class UpdateNoteForm(ModelForm):
    class Meta:
        model = Note
        # fields = "__all__"
        fields = ["title","note","category","done"]
        widgets = {
            "title": forms.TextInput(attrs={'class':'form-control'}),
            "note": forms.Textarea(attrs={'class':'form-control'}),
            "category": forms.Select(attrs={'class':'form-control'}),
        }

notes/views.py
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView, TemplateView
from notes.models import Note
from django.urls import path
from django.urls import reverse_lazy
from notes.forms import NoteForm, UpdateNoteForm


class DashboardTemplateView(TemplateView):
    template_name = "notes/dashboard.html"


class NoteListView(ListView):
    model = Note
    queryset = Note.objects.filter(trash=False).order_by("-updated_date").all()
    context_object_name = "notes_list"


class CreateNoteView(CreateView):
    model = Note
    # fields = ["title", "note", "category"]
    form_class = NoteForm
    success_url = reverse_lazy("notes:notes_list")


class NoteDetailView(DetailView):
    model = Note


class NoteDeleteView(DeleteView):
    model = Note
    success_url = reverse_lazy("notes:notes_list")


class MoveNoteToTrashView(UpdateView):
    model = Note
    fields = ["trash"]
    template_name = "notes/move_note_trash.html"
    success_url = reverse_lazy("notes:notes_list")


class TrashNoteView(ListView):
    model = Note
    queryset = Note.objects.filter(trash=True).order_by("id").all()
    context_object_name = "trash_notes_list"
    template_name = "notes/trash_notes_list.html"


class RestoreTrashNote(UpdateView):
    model = Note
    fields = ["trash"]
    success_url = reverse_lazy("notes:notes_list")
    template_name = "notes/trash-note-move-to-note.html"


class NoteUpdateView(UpdateView):
    model = Note
    # fields = ["title", "note", "done", "category"]
    form_class = UpdateNoteForm
    success_url = reverse_lazy("notes:notes_list")


class DoneNoteView(ListView):
    model = Note
    queryset = Note.objects.filter(done=True).filter(trash=False).all()
    context_object_name = "done_notes"
    template_name = "notes/done-notes.html"


class PendingNoteView(ListView):
    model = Note
    queryset = Note.objects.filter(done=False).filter(trash=False).all()
    context_object_name = "pending_notes"
    template_name = "notes/pending-notes.html"

notes/templates/notes/done-notes.html
{% extends "base.html" %}
<!--  -->
{% load humanize %}
<!--  -->
{% block title %} Done Tasks {% endblock %}
<!--  -->

{% block content %}
<!--  -->

<table class="table">
  <thead class="table-light">
    <tr>
      <th>ID</th>
      <th style="min-width: 400px">TITLE</th>
      <th>CATEGORY</th>
      <th>STATUS</th>
      <th>LAST VISIT</th>
      <th>VIEW</th>
      <th>UPDATE</th>
      <th>DELETE</th>
    </tr>
  </thead>
  <tbody>
    {% for note in done_notes %}
    <tr>
      <td>{{ note.id }}</td>
      <td>
        <a
          href="{% url 'notes:notes-detail' note.id %}"
          style="text-decoration: none; font-weight: bold; font-size: 1rem"
          >{{ note.title }}</a
        >
      </td>
      <td>{{ note.category }}</td>
      <td>
        {% if note.done %}
        <a href="" style="color: green">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="20"
            fill="currentColor"
            class="bi bi-check-circle-fill"
            viewBox="0 0 16 16"
          >
            <path
              d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"
            />
          </svg>
        </a>
        {% else %}
        <a href="" style="color: red">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="22"
            height="22"
            fill="currentColor"
            class="bi bi-hourglass"
            viewBox="0 0 16 16"
          >
            <path
              d="M2 1.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1-.5-.5zm2.5.5v1a3.5 3.5 0 0 0 1.989 3.158c.533.256 1.011.791 1.011 1.491v.702c0 .7-.478 1.235-1.011 1.491A3.5 3.5 0 0 0 4.5 13v1h7v-1a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351v-.702c0-.7.478-1.235 1.011-1.491A3.5 3.5 0 0 0 11.5 3V2h-7z"
            />
          </svg>
        </a>
        {% endif %}
      </td>
      <td>{{ note.updated_date | naturaltime }}</td>
      <td>
        <a href="{% url 'notes:notes-detail' note.id %}">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="currentColor"
            class="bi bi-eye-fill"
            viewBox="0 0 16 16"
          >
            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z" />
            <path
              d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"
            />
          </svg>
        </a>
      </td>
      <td>
        <a href="{% url 'notes:update-note' note.id %}" class="m-3">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="currentColor"
            class="bi bi-pencil-square"
            viewBox="0 0 16 16"
          >
            <path
              d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"
            />
            <path
              fill-rule="evenodd"
              d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
            />
          </svg>
        </a>
      </td>
      <td>
        <a href="{% url 'notes:move-note-trash' note.id %}" style="color: red">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            fill="currentColor"
            class="bi bi-trash"
            viewBox="0 0 16 16"
          >
            <path
              d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
            />
            <path
              fill-rule="evenodd"
              d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
            />
          </svg>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!--  -->
{% endblock %}

notes/templates/notes/note_detail.html
{% extends "base.html" %}

<!--  -->

{% block content %}

<h1>Note Detail</h1>

<div class="card" style="width: 100%">
  <div class="card-body">
    <h5 class="card-title">{{ note.title }}</h5>
    <p class="card-text">{{ note.note }}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><b>Category : </b>{{ note.category }}</li>
    <li class="list-group-item">
      <b>Last Updated Date : </b>{{ note.updated_date|date:'d F Y, g:i A' }}
    </li>
    <li class="list-group-item">
      <b>Created Date : </b>{{ note.created_date|date:'d F Y, g:i A' }}
    </li>
    <li class="list-group-item">
      <b> Status : </b>
      {% if note.done %} Completed {% else %} Pending {% endif %}
    </li>
  </ul>
  <div class="card-body">
    <a href="{% url 'notes:update-note' note.id %}" class="m-3">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        fill="currentColor"
        class="bi bi-pencil-square"
        viewBox="0 0 16 16"
      >
        <path
          d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"
        />
        <path
          fill-rule="evenodd"
          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
        />
      </svg>
    </a>
    <a href="{% url 'notes:delete-note' note.id %}" style="color: red">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        fill="currentColor"
        class="bi bi-trash"
        viewBox="0 0 16 16"
      >
        <path
          d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
        />
        <path
          fill-rule="evenodd"
          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
        />
      </svg>
    </a>
  </div>
</div>

{% endblock %}

templates/sidebar.html
<nav
  id="sidebarMenu"
  class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
>
  <div class="position-sticky pt-3 sidebar-sticky">
    <ul class="nav flex-column">
      <!-- dashboard -->
      <li class="nav-item">
        <a
        {% if '/' == request.path %}
          class="nav-link active"
          {% else %}
            class="nav-link"
          {% endif %}
          aria-current="page"
          href="{% url 'notes:dashboard' %}"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="feather feather-home align-text-bottom"
            aria-hidden="true"
          >
            <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
            <polyline points="9 22 9 12 15 12 15 22"></polyline>
          </svg>
          Dashboard
        </a>
      </li>

      <!-- notes -->
      <li class="nav-item">
        <a 
        {% if '/add/' == request.path %}
        class="nav-link active"
        {% else %}
        class="nav-link"
        {% endif %}
         href="{% url 'notes:create_note' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
</svg>
          New Notes
        </a>
      </li>

      <!-- notes -->
      <li class="nav-item">
        <a 
        {% if '/notes/' == request.path %}
        class="nav-link active"
        {% else %}
        class="nav-link"
        {% endif %}
         href="{% url 'notes:notes_list' %}">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="feather feather-file align-text-bottom"
            aria-hidden="true"
          >
            <path
              d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"
            ></path>
            <polyline points="13 2 13 9 20 9"></polyline>
          </svg>
          Notes
        </a>
      </li>

      <!-- completed note -->
      <li class="nav-item">
        <a 
        {% if '/done-notes/' == request.path %}
        class="nav-link active"
        {% else %}
        class="nav-link"
        {% endif %}
         href="{% url 'notes:done_notes' %}">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-check-lg"
            viewBox="0 0 16 16"
          >
            <path
              d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"
            />
          </svg>
          Completed
        </a>
      </li>

      <!-- pending -->
      <li class="nav-item">
        <a 
        {% if '/pending-note/' == request.path %}
        class="nav-link active"
        {% else %}
        class="nav-link"
        {% endif %}
        href="{% url 'notes:pending_notes' %}">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-hourglass"
            viewBox="0 0 16 16"
          >
            <path
              d="M2 1.5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-1v1a4.5 4.5 0 0 1-2.557 4.06c-.29.139-.443.377-.443.59v.7c0 .213.154.451.443.59A4.5 4.5 0 0 1 12.5 13v1h1a.5.5 0 0 1 0 1h-11a.5.5 0 1 1 0-1h1v-1a4.5 4.5 0 0 1 2.557-4.06c.29-.139.443-.377.443-.59v-.7c0-.213-.154-.451-.443-.59A4.5 4.5 0 0 1 3.5 3V2h-1a.5.5 0 0 1-.5-.5zm2.5.5v1a3.5 3.5 0 0 0 1.989 3.158c.533.256 1.011.791 1.011 1.491v.702c0 .7-.478 1.235-1.011 1.491A3.5 3.5 0 0 0 4.5 13v1h7v-1a3.5 3.5 0 0 0-1.989-3.158C8.978 9.586 8.5 9.052 8.5 8.351v-.702c0-.7.478-1.235 1.011-1.491A3.5 3.5 0 0 0 11.5 3V2h-7z"
            />
          </svg>
          Pendings
        </a>
      </li>

      <!-- remainders -->
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-bell"
            viewBox="0 0 16 16"
          >
            <path
              d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"
            />
          </svg>
          Remind Me
        </a>
      </li>

      <!-- trash -->
      <li class="nav-item">
        <a
        {% if '/trash-note-view/' == request.path %}
        class="nav-link active" 
        {% else %}
        class="nav-link" 
        {% endif %}
        href="{% url 'notes:trash-note-view' %}">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-trash"
            viewBox="0 0 16 16"
          >
            <path
              d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
            />
            <path
              fill-rule="evenodd"
              d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
            />
          </svg>
          Trash
        </a>
      </li>
    </ul>

    <h6
      class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase"
    >
      <span>Profile</span>
      <a class="link-secondary" href="#" aria-label="Add a new report">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="feather feather-plus-circle align-text-bottom"
          aria-hidden="true"
        >
          <circle cx="12" cy="12" r="10"></circle>
          <line x1="12" y1="8" x2="12" y2="16"></line>
          <line x1="8" y1="12" x2="16" y2="12"></line>
        </svg>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <!-- profile -->
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-file-earmark-person"
            viewBox="0 0 16 16"
          >
            <path d="M11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
            <path
              d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2v9.255S12 12 8 12s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h5.5v2z"
            />
          </svg>
          Profile
        </a>
      </li>

      <!-- settings -->
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-gear-fill"
            viewBox="0 0 16 16"
          >
            <path
              d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"
            />
          </svg>
          Account Settings
        </a>
      </li>

      <!-- sign out -->
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-box-arrow-right"
            viewBox="0 0 16 16"
          >
            <path
              fill-rule="evenodd"
              d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"
            />
            <path
              fill-rule="evenodd"
              d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"
            />
          </svg>
          Sign Out
        </a>
      </li>
    </ul>
  </div>
</nav>